substitutions:
  _MONGO_URI: ""
  _SECRET_KEY: ""

steps:
  # 1) Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/wish-tree'
      - '.'

  # 2) 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/wish-tree'

  # 3) Cloud Run 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'wish-tree'
      - '--image=gcr.io/$PROJECT_ID/wish-tree'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=MONGO_URI=${_MONGO_URI},SECRET_KEY=${_SECRET_KEY}'
#  - name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        gcloud run deploy wish-tree \
#          --image gcr.io/$PROJECT_ID/wish-tree \
#          --region asia-northeast3 \
#          --platform managed \
#          --allow-unauthenticated \
#          --set-env-vars="MONGO_URI=$$_MONGO_URI,SECRET_KEY=$$_SECRET_KEY"

  # 4) substitution 변수 dummy 사용 (인식용)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       echo ${_MONGO_URI}
       echo ${_SECRET_KEY}
      
images:
  - 'gcr.io/$PROJECT_ID/wish-tree'

timeout: 1200s

